name: Build and Push to ACR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to ACR
        run: |
          docker login testconregyhg.azurecr.io \
            -u testConRegyhg \
            -p K4llvmLUB9nDd3Wiza0BMEX5Ls3lEUqR0dwtIMD/bb+ACRAd10kL

      - name: Build and Push
        run: |
          docker build -t testconregyhg.azurecr.io/chicken:${{ github.sha }} .
          docker push testconregyhg.azurecr.io/chicken:${{ github.sha }}
